### ISSUE TITLE
Unable to download JS bundle

### ISSUE THREAD

**Issue by NoWay1201** [react-native-material-design/react-native-material-design#15]
Hi,

I have a problem when trying to run this in my app. When I'm not importing 'react-native-material-design', my app is working well - but when I'm adding import, my app crashes (packager transforming 461/463 and stopping in this place, and on phone I can see "Unable to download JS bundle").
I'm new in react native, and I'm working on android only. If someone can help me I will be grateful.

**Comment by Ehesp** [comment]
Hello

What version of React Native do you have, along with the device/Android API you're on?

Also could you show some code?

Cheers

**Comment by NoWay1201** [comment]
My React Native version is 0.18.0-rc, device is Sony Xperia Z3 5.1.1 with API 22 and 23 installed. Code of my Component is:

```
import React, {AppRegistry, StyleSheet, Text, View, ListView, Image, TouchableOpacity} from 'react-native'
import { Actions } from 'react-native-router-flux'
import { Avatar } from 'react-native-material-design'

const Flights = React.createClass({
  getInitialState: function() {
    let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
    return {
      flights: ds.cloneWithRows([]),
    };
  },

  componentDidMount: function() {
    this.fetchData();
  },

  fetchData: function() {
    fetch('data_fetch_link')
      .then((response) => response.json())
      .then((responseData) => {
        let ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
        this.setState({
          flights: ds.cloneWithRows(responseData),
        });
      })
      .done();
  },

  render: function() {
    let flights = this.state.flights;

    return (
      <View style={styles.container}>
        <ListView
            dataSource={this.state.flights}
            renderRow={(rowData) =>
              <TouchableOpacity onPress={()=>Actions.Flight({flight: rowData})}>
                <View style={styles.card}>
                  <Text>{rowData.uuid}</Text>
                </View>
              </TouchableOpacity>
            }
        />
      </View>
    );
  }
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  card: {
    height: 80,
    borderStyle: 'solid',
    borderBottomWidth: 1,
    borderBottomColor: '#666666',
  },
  image: {
    width: 60,
    height: 80,
  }
});

module.exports = Flights;

```

**Comment by Ehesp** [comment]
Hmm. I did think it might be cause it's in ES5. Can you try with 0.17 and see if it works? I'll test when I can.

**Comment by Salakar** [comment]
Also, @NoWay1201 can you show the full error please so we can investigate further.

**Comment by NoWay1201** [comment]
@Ehesp when running with 0.17 i got following error:
"node_modules/react-native-material-design/lib/polyfill/Ripple.js: A semicolon is required after a class property (42:5)". When I'm adding the semicolon, got this:
"'ScrollView' has no propType for native prop RCTScrollView.sendMomentumEvents' of native type 'boolean'".

@Salakar here you are:
Phone:
![screenshot_2016-01-07-23-45-26](https://cloud.githubusercontent.com/assets/11422162/12185052/38693a48-b599-11e5-87a6-0b936d4ca2fb.png)
And packager: (it is stucked like that)
![packager](https://cloud.githubusercontent.com/assets/11422162/12185059/3d275bbe-b599-11e5-8407-9ac8d8c677d1.png)

**Comment by Ehesp** [comment]
@NoWay1201 I don't think it's properly downgraded from 0.18-rc - see https://github.com/facebook/react-native/issues/5191 seems to be related. Did you try it again by downgrading or fresh-install with 0.17?

**Comment by NoWay1201** [comment]
@Ehesp I tried to downgrade it to 0.17 again, and still the same error: "A semicolon is required after a class property". My global react-native is 0.1.7 and in package.json I have "react-native": "0.17.0" and when running npm install after rm-rf node_modules it shows me that it's downloading reac-tnative 0.17, so it should be good, or maybe I'm wrong? I simplified my file:
```
'use strict';

import React, {AppRegistry, StyleSheet, Text, View, ListView, Image, TouchableOpacity} from 'react-native'
import { Actions } from 'react-native-router-flux'
import { Avatar } from 'react-native-material-design'

const Flights = React.createClass({
  render: function() {
    return (
      <Text>Test</Text>
    )
  }
});

module.exports = Flights;
```
And without import it's working, but with "A semicolon is required after a class poperty".

**Comment by Ehesp** [comment]
Could I see your android/app/build.gradle file too please?

**Comment by NoWay1201** [comment]
Sure:
```
apply plugin: "com.android.application"

/**
 * The react.gradle file registers two tasks: bundleDebugJsAndAssets and bundleReleaseJsAndAssets.
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"]
 * ]
 */

apply from: "react.gradle"

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.xcp4_flights_new"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled false  // Set this to true to enable Proguard
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:0.18.+"
}
```
I can say, that when i added this 3 semicolons, it started working

**Comment by Ehesp** [comment]
Very bottom, you're still running the app on 18:

compile "com.facebook.react:react-native:0.18.+"

Change that back and try to reinstall. I'm pretty confident it's an 0.18
issue, seen a few issues about this but it should be fixed for official
release.

**Comment by NoWay1201** [comment]
When I'm setting it to 
`compile "com.facebook.react:react-native:0.17.0"`
got this in console when trying to `react-native run-android`:
```
:app:generateDebugSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/home/noway/xcp4_flights_new/android/app/src/main/java/com/xcp4_flights_new/MainActivity.java:3: error: cannot find symbol
import com.facebook.react.ReactActivity;
                         ^
  symbol:   class ReactActivity
  location: package com.facebook.react
/home/noway/xcp4_flights_new/android/app/src/main/java/com/xcp4_flights_new/MainActivity.java:10: error: cannot find symbol
public class MainActivity extends ReactActivity {
                                  ^
  symbol: class ReactActivity
/home/noway/xcp4_flights_new/android/app/src/main/java/com/xcp4_flights_new/MainActivity.java:16: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/noway/xcp4_flights_new/android/app/src/main/java/com/xcp4_flights_new/MainActivity.java:25: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/noway/xcp4_flights_new/android/app/src/main/java/com/xcp4_flights_new/MainActivity.java:34: error: method does not override or implement a method from a supertype
    @Override
    ^
5 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.064 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by Ehesp** [comment]
Can you come onto Gitter? Can help out better there https://gitter.im/react-native-material-design/react-native-material-design

**Comment by zoontek** [comment]
@Ehesp @NoWay1201 I've just made a PR to fix this.

**Comment by Salakar** [comment]
@Ehesp @zoontek @NoWay1201 fix has been published to npm. Thanks again @zoontek .

**Comment by Salakar** [comment]
Closing as issue resolved. Re-open if you have anymore related issues. Thanks!

**Comment by pewh** [comment]
Currently this repo doesn't work on RN 0.18/0.18.1, right?
I got same error running on device: `"'ScrollView' has no propType for native prop RCTScrollView.sendMomentumEvents' of native type 'boolean'"`. But no error on genymotion.

Also it's work if I downgrade to 0.17 :/
But I need 0.18 very much because it can split build per architecture so the APK size is much smaller

**Comment by Ehesp** [comment]
I'll look into this, I'm pretty sure that the demo app is running on 18.
Any particular component?

**Comment by pewh** [comment]
Oops. It's my bad. I've fix my problem by deleting file `app/src/main/assets/index.android.bundle` which cause the error on RN 0.18. So it's not an issue on your repo.
